services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: NbDQKegGMSNiDcBucWbxfCpxdXVorfhi
      MYSQL_DATABASE: railway
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network
  mongodb:
    image: mongo:latest
    container_name: ecommerce_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: marcelintingougoui3
      MONGO_INITDB_ROOT_PASSWORD: cagKxCWdDrWqt8md
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce_network
  redis:
    image: redis
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db
    networks:
      - ecommerce_network
  products-api:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: products_api
    environment:
      DATABASE_URL: mysql://root:NbDQKegGMSNiDcBucWbxfCpxdXVorfhi@mysql:3306/railway
    ports:
      - "3030:3030"
    depends_on:
      - mysql
    networks:
      - ecommerce_network
    command: >
      sh -c "npx prisma generate && npx prisma db push && npm run start"
  search-api:
    build:
      context: ./search
      dockerfile: Dockerfile
    container_name: search_api
    environment:
      DATABASE_URL: mysql://root:NbDQKegGMSNiDcBucWbxfCpxdXVorfhi@mysql:3306/railway
      REDIS_HOST: redis
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    networks:
      - ecommerce_network
    command: >
      sh -c "npx prisma generate && npx prisma db push && npm run start"

  newsletter-api:
    build:
      context: ./newsletter
      dockerfile: Dockerfile
    container_name: newsletter_api
    environment:
      DATABASE_URL: mongodb://marcelintingougoui3:cagKxCWdDrWqt8md@mongodb:27017/email?authSource=admin
    ports:
      - "3232:3232"
    depends_on:
      - mongodb
    networks:
      - ecommerce_network
  api-getway:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: api_getway
    environment:
      PRODUCT_SERVICE_URL: "http://products-api:3030"
      NEWSLETTER_SERVICE_URL: "http://newsletter-api:3232"
      SEARCH_SERVICE_URL: "http://search-api:3000"
    ports:
      - "3001:3001"
    depends_on:
      - products-api
      - newsletter-api
      - search-api
    networks:
      - ecommerce_network

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  ecommerce_network:
    driver: bridge
